### PR TITLE
Add flow.rc

### PR DESCRIPTION
**Pull request by wxtim**
I think that these two files should be added to the list of those identified for parsing. Whilst the global config format is not _exactly_ the same as the `suite.rc` format I think it's sufficiently similar for this to be a good idea®.

### CODE REVIEW

**Comment by MetRonnie** [comment]
I was literally just thinking about that this morning

**Review by MetRonnie — APPROVED** [review]

**Comment by oliver-sanders** [comment]
Heads up, these filenames will only ever make an appearance in alpha versions, by release time we will have moved to the universal `.cylc` extension (which is much easier to configure).

But still, no harm.

**Review by oliver-sanders — APPROVED** [review]

**Comment by MetRonnie** [comment]
Btw, @wxtim I personally believe it is better to rebase on master rather than to merge master into a topic branch, where possible/feasible. It keeps the git log graph cleaner, especially when the topic branch originally branched off master many commits ago

**Comment by wxtim** [comment]
Totally agree Ronnie - I was trying to do it entirely on GH and made a mess of things.

**Comment by MetRonnie** [comment]
Oh yeah, I think that's the problem Mel had with her authentication washup PR a few weeks ago. The GH instructions can be a bit funny

**Pull request merged**
